      SUBROUTINE SM_DEVICE (TEXT)
      CHARACTER TEXT*(*)
      ENTRY SM_GRAPHICS
      ENTRY SM_ERASE
      ENTRY SM_LOCATION (I, J, K, L)
      ENTRY SM_LIMITS (W, X, Y, Z)
      ENTRY SM_BOX (I, J, K, L)
      ENTRY SM_RELOCATE (X, Y)
      ENTRY SM_DRAW (X, Y)
      ENTRY SM_GFLUSH
      ENTRY SM_ALPHA
      ENTRY SM_PUTLABEL (I, TEXT)
      ENTRY SM_XLABEL (TEXT)
      ENTRY SM_YLABEL (TEXT)
      ENTRY SM_DOT
      ENTRY SM_LWEIGHT (I)
      ENTRY SM_EXPAND (X)
      ENTRY SM_PTYPE (X, I)
      RETURN
      END
